[package]
name = "minimal_baremetal"
version = "0.1.0"
authors = ["Niket Naidu <coder137@gmail.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
